apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system-deployment
  namespace: solar-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
        - name: apache-container
          image: httpd:latest
          ports:
            - containerPort: 8080
