apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-password
  namespace: solar-namespace
spec:
  encryptedData:
    password: AgCQBoEdkkUZ5vJraNQ7Gf7KEyZddigZVMXJyjpdztNAoRjxeCyj5B2RYhEjNCfsMaxsTw0hGK2Ggk1WkB8v0z6TXeYk6TUo07ezzeWP9NZgOGb9GmZm1bBtnpKz8NHsPiPXJdCfyWfl6mFtft+S65NA58CLeNM0FGgaiThbPFEMKRScZGbsnNEJGnnoAwJ4cyxoxgpo2DDacypnlHSMQzYC4uiPBx09ojjr/6IdaKWDsVrnJoom56cr9SpErQMu69ukNJ5VsXerLF+Q+YEW/Qf8/KIDfu86ah5nFJxIa6HyctBRKnQG2yXhh7d4XD7MkweZVTUQ8/c0JMISxTpk+4RjhNvr2aJB4UQTjNIasWsdNsYYKoHWMtXosHsjm3498hTWXqfrdHgGsybaHaqnTglEcD4o52yakKpxBoHt7YKI+fjQT2L5wN8iy/3NAO1Fp9rUCuTWKgYt0n6cuEbMF0FXBoFTkj3+SbLCcKHwr4rTsxhnEis5iS7zA9+zX+wSIbHKG17nSp6IGJp02iPjWcf7rrNTe0ZDuLvturotHql98ktGSayW++f2M98YScIpZiRxzxZJ1PLoIL+XifQr/aBb5x6rJ3E5fgrkh+0iQ+mmqFPwt1Q/uR7QuXTSBDKI0AtQX8vdst4dr/LpX4F0+18eQ7mjt1ZKPLHQy/3KW2hbrC8L1AikRbBNwlPvXE5NGkHPOUHry951u3yncaoR
  template:
    metadata:
      name: mysql-password
      namespace: solar-namespace
    type: Opaque
